- name: frontend configuration
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: copy conf file
      ansible.builtin.copy:
        src: nginx-roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: clean old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: present

    - name: Create app directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download & Extract Application Content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: start nginx srvice
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true










