- name: disable default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app prerequisites
  ansible.builtin.import_tasks: app-preq.yml

- name: install dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: mongo schema load
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: systemd setup
  ansible.builtin.import_tasks: systemd-setup.yml