- name: install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: app prerequisites
  ansible.builtin.import_tasks: app-preq.yml

- name: install dependencies
  ansible.builtin.shell: go mod init {{component}} ; go get ; go build
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_tasks: systemd-setup.yml